### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by AndriiBash** [AndriiBash/Gradify#11]
# Settings window
- [ ] Select the application theme
- [ ] Language selection
- [ ] Select app accent color
- [ ] Remake filtering for sorting (by date, by name, etc.)
